### ISSUE TITLE
Migration to version 8

### ISSUE THREAD

**Issue by max3903** [OCA/vertical-travel#30]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-8
# Modules to migrate
- [ ] airline  
- [ ] airline_data
- [ ] airport
- [ ] airport_data
- [ ] motor_vehicle
- [ ] passport_expiration
- [ ] railway_company
- [ ] railway_station
- [ ] transportation
- [x] travel
- [ ] travel_accommodation
- [ ] travel_hr
- [ ] travel_journey by @houssine78 in #37 
- [ ] travel_journey_hr
- [ ] travel_journey_other
- [ ] travel_journey_plane
- [ ] travel_journey_rail
- [ ] travel_passport
- [ ] travel_purchase  
- [ ] travel_rental_car
- [ ] travel_rental_service
