### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-travel#47]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] airline
- [ ] airline_data
- [ ] airport
- [ ] airport_data
- [ ] motor_vehicle
- [ ] passport_expiration
- [ ] railway_company
- [ ] railway_station
- [ ] transportation
- [ ] travel
- [ ] travel_accommodation
- [ ] travel_hr
- [ ] travel_journey
- [ ] travel_journey_hr
- [ ] travel_journey_other
- [ ] travel_journey_plane
- [ ] travel_journey_rail
- [ ] travel_passport
- [ ] travel_purchase
- [ ] travel_rental_car
- [ ] travel_rental_service
